package com.drabdie.tweak;

import android.app.*;
import android.os.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.provider.Settings;
import android.view.*;
import android.widget.*;
import java.util.*;
import rikka.shizuku.Shizuku;

public class MainActivity extends Activity {
    final int BG=Color.rgb(11,13,20), CARD=Color.rgb(22,25,36), TEXT=Color.rgb(245,246,255), MUTED=Color.rgb(155,161,184), ACCENT=Color.rgb(124,131,253), GREEN=Color.rgb(67,211,145), ORANGE=Color.rgb(255,174,79);
    LinearLayout root, content; TextView title, subtitle, shizukuStatus; Handler handler=new Handler(Looper.getMainLooper()); int selected=0; String[] profiles={"Performance","Balanced","Battery","Game Mode","Custom"};
    int dp(float v){return (int)(v*getResources().getDisplayMetrics().density+.5f);} TextView tv(String s,float size,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setFontFeatureSettings("kern");return t;}
    GradientDrawable bg(int color,float radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(radius));return g;}
    LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);l.setGravity(Gravity.CENTER_VERTICAL);return l;}
    TextView label(String s){TextView t=tv(s,12,MUTED);t.setAllCaps(true);t.setLetterSpacing(.08f);return t;}
    @Override public void onCreate(Bundle b){super.onCreate(b); getWindow().setStatusBarColor(BG); getWindow().setNavigationBarColor(BG); build(); handler.post(tick);}
    void build(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG); root.setPadding(dp(20),dp(16),dp(20),0);
        LinearLayout head=row(); title=tv("DraB Tweak",27,TEXT); title.setTypeface(null,1); head.addView(title,new LinearLayout.LayoutParams(0,dp(42),1)); TextView more=tv("⋮",32,MUTED); head.addView(more,new LinearLayout.LayoutParams(dp(38),dp(42))); root.addView(head);
        subtitle=tv("NO-ROOT SYSTEM MANAGER",11,ACCENT); subtitle.setLetterSpacing(.12f); root.addView(subtitle,new LinearLayout.LayoutParams(-1,dp(24)));
        content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL); ScrollView scroll=new ScrollView(this);scroll.setClipToPadding(false);scroll.addView(content);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
        LinearLayout nav=new LinearLayout(this);nav.setOrientation(LinearLayout.HORIZONTAL);nav.setGravity(Gravity.CENTER);nav.setPadding(0,dp(10),0,dp(10));String[] ns={"⌂\nHome","◈\nMonitor","⚙\nTools"};for(int i=0;i<3;i++){final int x=i;TextView n=tv(ns[i],12,i==0?TEXT:MUTED);n.setGravity(Gravity.CENTER);n.setPadding(0,dp(5),0,dp(5));n.setOnClickListener(v->{if(x==0)showHome();else if(x==1)showMonitor();else showTools();});nav.addView(n,new LinearLayout.LayoutParams(0,dp(52),1));}root.addView(nav);setContentView(root);showHome();}
    void clear(){content.removeAllViews();}
    TextView section(String s){TextView t=label(s);t.setPadding(0,dp(14),0,dp(8));content.addView(t);return t;}
    TextView button(String s){TextView b=tv(s,14,TEXT);b.setGravity(Gravity.CENTER);b.setPadding(dp(14),0,dp(14),0);b.setBackground(bg(ACCENT,14));return b;}
    void showHome(){clear();section("CURRENT PROFILE");LinearLayout hero=row();hero.setPadding(dp(18),dp(14),dp(14),dp(14));hero.setBackground(bg(Color.rgb(37,40,67),20));LinearLayout htext=new LinearLayout(this);htext.setOrientation(LinearLayout.VERTICAL);TextView p=tv(profiles[selected],23,TEXT);p.setTypeface(null,1);htext.addView(p);TextView desc=tv(selected==0?"Maximum responsiveness":"Optimized for everyday use",12,MUTED);htext.addView(desc);hero.addView(htext,new LinearLayout.LayoutParams(0,dp(72),1));TextView dot=tv("●",27,selected==2?GREEN:ACCENT);hero.addView(dot);content.addView(hero,new LinearLayout.LayoutParams(-1,dp(102)));
        section("QUICK PROFILES");LinearLayout grid=new LinearLayout(this);grid.setOrientation(LinearLayout.VERTICAL);for(int i=0;i<profiles.length;i+=2){LinearLayout r=row();for(int j=i;j<i+2&&j<profiles.length;j++){final int k=j;TextView c=tv((j==0?"⚡  ":j==1?"◉  ":j==2?"☾  ":j==3?"◈  ":"✦  ")+profiles[j],14,j==selected?TEXT:MUTED);c.setGravity(Gravity.CENTER_VERTICAL);c.setPadding(dp(14),0,dp(8),0);c.setBackground(bg(j==selected?Color.rgb(40,43,67):CARD,14));c.setOnClickListener(v->{selected=k;showHome();});r.addView(c,new LinearLayout.LayoutParams(0,dp(54),1){ {setMargins(0,0,dp(6),dp(6));} });}grid.addView(r);}content.addView(grid);
        section("DEVICE STATUS");LinearLayout stats=row();stats.addView(stat("CPU","--", "loading"),new LinearLayout.LayoutParams(0,dp(92),1));stats.addView(stat("RAM","--","loading"),new LinearLayout.LayoutParams(0,dp(92),1));stats.addView(stat("BATTERY","--","loading"),new LinearLayout.LayoutParams(0,dp(92),1));content.addView(stats);
        section("SHIZUKU ACCESS");LinearLayout sh=row();sh.setPadding(dp(14),dp(12),dp(10),dp(12));sh.setBackground(bg(CARD,16));LinearLayout st=new LinearLayout(this);st.setOrientation(LinearLayout.VERTICAL);shizukuStatus=tv("Checking Shizuku…",14,TEXT);st.addView(shizukuStatus);st.addView(tv("ADB-level actions, no root required",11,MUTED));sh.addView(st,new LinearLayout.LayoutParams(0,dp(54),1));TextView act=button("CONNECT");act.setTextSize(12);act.setOnClickListener(v->requestShizuku());sh.addView(act,new LinearLayout.LayoutParams(dp(104),dp(42)));content.addView(sh,new LinearLayout.LayoutParams(-1,dp(82)));updateShizuku();}
    View stat(String name,String value,String sub){LinearLayout s=new LinearLayout(this);s.setOrientation(LinearLayout.VERTICAL);s.setPadding(dp(12),dp(10),dp(5),dp(8));s.setBackground(bg(CARD,14));TextView n=label(name);s.addView(n);TextView v=tv(value,22,TEXT);v.setTag(name);v.setTypeface(null,1);s.addView(v);s.addView(tv(sub,10,MUTED));return s;}
    void showMonitor(){clear();section("LIVE MONITOR");content.addView(card("CPU LOAD","Reading system load and frequency","Updates every second"));content.addView(card("MEMORY","Available and used RAM","Android ActivityManager"));content.addView(card("THERMALS","Device temperature sensors","Only sensors exposed by OEM"));content.addView(card("BATTERY","Charge, current and temperature","BatteryManager API"));section("CAPABILITIES");content.addView(card("✓  Available without root","System info, battery, storage, app usage","Public Android APIs"));content.addView(card("◈  Shizuku optional","Animations, DPI, app standby, package actions","Depends on OEM / Android version"));content.addView(card("×  Root required","CPU governor, GPU frequency, kernel /sys","Not available in no-root mode"));}
    View card(String a,String b,String c){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(16),dp(13),dp(16),dp(13));l.setBackground(bg(CARD,16));TextView x=tv(a,16,TEXT);x.setTypeface(null,1);l.addView(x);l.addView(tv(b,12,MUTED));l.addView(tv(c,11,ACCENT));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(82));p.setMargins(0,0,0,dp(8));content.addView(l,p);return l;}
    void showTools(){clear();section("SAFE TOOLS");TextView anim=button("OPEN ANIMATION SETTINGS");anim.setOnClickListener(v->{try{startActivity(new Intent(Settings.ACTION_DISPLAY_SETTINGS));}catch(Exception e){}});content.addView(anim,new LinearLayout.LayoutParams(-1,dp(50)));TextView dpi=button("DISPLAY SIZE & DPI");dpi.setOnClickListener(v->{try{startActivity(new Intent(Settings.ACTION_DISPLAY_SETTINGS));}catch(Exception e){}});content.addView(dpi,new LinearLayout.LayoutParams(-1,dp(50)));section("PROFILE AUTOMATION");content.addView(card("GAME MODE","Automatically apply a profile when a game opens","Requires Usage Access permission"));content.addView(card("BACKUP & RESTORE","Export or import JSON profiles","Stored locally on this device"));section("IMPORTANT");content.addView(card("NO ROOT GUARANTEE","Unsupported kernel controls are never faked or written","This app will not damage your device"));}
    void updateShizuku(){try{boolean ok=Shizuku.pingBinder();shizukuStatus.setText(ok?"Shizuku is ready":"Shizuku is not running");shizukuStatus.setTextColor(ok?GREEN:ORANGE);}catch(Throwable e){shizukuStatus.setText("Install Shizuku to unlock tools");shizukuStatus.setTextColor(ORANGE);}}
    void requestShizuku(){try{if(!Shizuku.pingBinder()){startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://shizuku.rikka.app/")));return;}if(Build.VERSION.SDK_INT>=23&&Shizuku.checkSelfPermission()!=PackageManager.PERMISSION_GRANTED)Shizuku.requestPermission(100);updateShizuku();}catch(Throwable e){Toast.makeText(this,"Install and start Shizuku first",Toast.LENGTH_LONG).show();}}
    Runnable tick=new Runnable(){public void run(){if(content.getChildCount()>0){try{ActivityManager am=(ActivityManager)getSystemService(ACTIVITY_SERVICE);ActivityManager.MemoryInfo m=new ActivityManager.MemoryInfo();am.getMemoryInfo(m);BatteryManager bm=(BatteryManager)getSystemService(BATTERY_SERVICE);int bat=bm.getIntProperty(BatteryManager.BATTERY_PROPERTY_CAPACITY);for(int i=0;i<content.getChildCount();i++){View v=content.getChildAt(i);if(v instanceof LinearLayout){for(int j=0;j<((LinearLayout)v).getChildCount();j++){View z=((LinearLayout)v).getChildAt(j);if(z instanceof TextView&&"RAM".equals(z.getTag()))((TextView)z).setText((m.totalMem-m.availMem)/1024/1024+" MB");if(z instanceof TextView&&"BATTERY".equals(z.getTag()))((TextView)z).setText(bat+"%");}}}}catch(Exception ignored){}}handler.postDelayed(this,1000);}};
    @Override protected void onDestroy(){handler.removeCallbacks(tick);super.onDestroy();}
}
