plugins { id 'com.android.application' }

android { namespace 'com.drabdie.tweak'; compileSdk 35
    buildFeatures { aidl true }
    defaultConfig { applicationId 'com.drabdie.tweak'; minSdk 24; targetSdk 35; versionCode 4; versionName '2.0.0' }
}

dependencies {
    implementation 'dev.rikka.shizuku:api:13.1.5'
}
